name: namespace
home: https://github.com/deis/workflow
version: 2.0.0-pre-alpha
description: The Deis namespace
maintainers:
- Matt Boersma <mboersma@deis.com>
details: |-
  This chart provides the master Deis namespace into which all other Deis
  components are deployed.
