#helm:generate helm tpl --out $HELM_GENERATE_DIR/manifests/controller-secret-builder-key-auth.yaml $HELM_GENERATE_DIR/tpl/controller-secret-builder-key-auth.yaml
apiVersion: v1
kind: Secret
metadata:
  name: builder-key-auth
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  builder-key: {{ randAscii 64 | b64enc }}
