apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-minio
  namespace: deis
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{env "MINIO_GIT_TAG" | default .minio.dockerTag}}
spec:
  replicas: 1
  selector:
    app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      serviceAccount: deis-minio
      containers:
        - name: deis-minio
          image: quay.io/{{.minio.org}}/minio:{{env "MINIO_GIT_TAG" | default .minio.dockerTag}}
          imagePullPolicy: {{.minio.pullPolicy}}
          env:
            - name: HEALTH_SERVER_PORT
              value: "8082"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
{{- if or (.minio.limits_cpu) (.minio.limits_memory)}}
          resources:
            limits:
{{- if (.minio.limits_cpu) }}
              cpu: {{.minio.limits_cpu}}
{{- end}}
{{- if (.minio.limits_memory) }}
              memory: {{.minio.limits_memory}}
{{- end}}
{{- end}}
          command:
            - boot
          args:
            - "server /home/minio/"
          volumeMounts:
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
        - name: minio-user
          secret:
            secretName: objectstorage-keyfile
