apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-minio
  namespace: deis
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{env "MINIO_GIT_TAG" | default .minio.dockerTag}}
spec:
  replicas: 1
  selector:
    app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      serviceAccount: deis-minio
      containers:
        - name: deis-minio
          image: quay.io/{{.minio.org}}/minio:{{env "MINIO_GIT_TAG" | default .minio.dockerTag}}
          imagePullPolicy: {{.minio.pullPolicy}}
          env:
            - name: HEALTH_SERVER_PORT
              value: "8082"
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          command:
            - boot
          args:
            - "server /home/minio/"
          volumeMounts:
{{- if ne .minio.hostPath ""}}
            - name: minio-home
              mountPath: /home/minio
{{- end }}
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
{{- if ne .minio.hostPath ""}}
        - name: minio-home
          hostPath:
            path: {{ .minio.hostPath }}
{{- end }}
        - name: minio-user
          secret:
            secretName: objectstorage-keyfile
