#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/logger-fluentd-daemon.yaml $HELM_GENERATE_FILE
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logger-fluentd
  namespace: deis
  labels:
    heritage: deis
spec:
  selector:
    matchLabels:
      app: logger-fluentd
      heritage: deis
  template:
    metadata:
      name: logger-fluentd
      labels:
        heritage: deis
        app: logger-fluentd
    spec:
      serviceAccount: logger-fluentd
      containers:
      - name: logger-fluentd
        image: quay.io/{{ .fluentd.org }}/fluentd:{{env "FLUENTD_GIT_TAG" | default .fluentd.dockerTag}}
        imagePullPolicy: {{.fluentd.pullPolicy}}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: SYSLOG_HOST
          value: $(DEIS_LOGGER_SERVICE_HOST)
        - name: SYSLOG_PORT
          value: $(DEIS_LOGGER_SERVICE_PORT_TRANSPORT)
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
