#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/logger-rc.yaml $HELM_GENERATE_DIR/tpl/logger-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: logger
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: quay.io/{{.logger.org}}/logger:{{env "LOGGER_GIT_TAG" | default .logger.dockerTag}}
        imagePullPolicy: {{.logger.pullPolicy}}
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 1514
          name: transport
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
