#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/minio-rc.yaml $HELM_GENERATE_DIR/tpl/minio-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: minio
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      serviceAccount: minio
      containers:
        - name: minio
          image: quay.io/{{.minio.org}}/minio:{{env "MINIO_GIT_TAG" | default .minio.dockerTag}}
          imagePullPolicy: {{.minio.pullPolicy}}
          env:
            - name: HEALTH_SERVER_PORT
              value: "8082"
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          command:
            - boot
          args:
            - "server /home/minio/"
          volumeMounts:
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
        - name: minio-user
          secret:
            secretName: minio-user
