#helm:generate helm template -o $HELM_GENERATE_DIR/manifests/registry-rc.yaml -d $HELM_GENERATE_DIR/tpl/generate_params.toml $HELM_GENERATE_DIR/tpl/registry-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      serviceAccount: registry
      containers:
        - name: registry
          image: quay.io/{{.registry.org}}/registry:{{env "REGISTRY_GIT_TAG" | default .registry.dockerTag}}
          imagePullPolicy: {{.registry.pullPolicy}}
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
            - name: REGISTRY_STORAGE
              value: {{default "minio" .storage}}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: registry-creds
              mountPath: /var/run/secrets/deis/registry/creds
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: registry-creds
          secret:
            secretName: objectstorage-keyfile
