apiVersion: v1
kind: Service
metadata:
  name: deis-database
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: deis-database
