name: workflow-rc2-e2e
home: https://github.com/deis/workflow-e2e
version: v2.0.0-rc2
description: |-
  End-to-end tests for Deis Workflow, executed in parallel
maintainers:
- Deis Team <engineering@deis.com>
details: |-
  End-to-end tests for the Deis Workflow open source PaaS, executed in parallel.

  Deis (pronounced DAY-iss) Workflow is an open source PaaS that makes it easy to deploy
  and manage applications on your own servers. Workflow builds on Kubernetes to provide a
  lightweight, Heroku-inspired workflow.
