apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: registry
