apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-registry
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-registry
  template:
    metadata:
      labels:
        app: deis-registry
    spec:
      serviceAccount: deis-registry
      containers:
        - name: deis-registry
          image: quay.io/deisci/registry:v2-beta
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          emptyDir: {}
