apiVersion: v1
kind: Service
metadata:
  name: deis-router
  namespace: deis
  labels:
    heritage: deis
spec:
  type: LoadBalancer
  selector:
    app: deis-router
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: builder
      port: 2222
      targetPort: 2222
    - name: healthz
      port: 9090
      targetPort: 9090
