kind: Service
apiVersion: v1
metadata:
  name: deis-etcd-1
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - name: peer
      port: 2380
      protocol: TCP
    - name: client
      port: 4100
  selector:
    app: deis-etcd-1
