apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-registry
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-registry
  template:
    metadata:
      labels:
        app: deis-registry
    spec:
      containers:
        - name: deis-registry
          image: quay.io/deis/registry:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          hostPath:
            path: /data/deis/registry
