apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-workflow
  template:
    metadata:
      labels:
        app: deis-workflow
    spec:
      containers:
        - name: deis-workflow
          image: quay.io/deis/workflow:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          env:
            - name: DEIS_DATABASE_USER
              value: deis
            - name: DEIS_DATABASE_PASSWORD
              value: changeme123
          ports:
            - containerPort: 8000
              name: http
              # expose port to node to make workflow to be accessable from host
              hostPort: 8000
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: minio-user
          secret:
            secretName: minio-user
