apiVersion: v1
kind: Service
metadata:
  name: deis-workflow
  namespace: deis
  labels:
    heritage: deis
    routable: "true"
  annotations:
    deis.io/routerConfig: |
      {
        "domains": [ "deis" ],
        "connectTimeout": 10,
        "tcpTimeout": 1200
      }
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: deis-workflow
