apiVersion: v1
kind: Service
metadata:
  name: deis-logger-redis
  namespace: deis
  labels:
    heritage: helm
  annotations:
    helm-keep: "true"
spec:
  selector:
    app: deis-logger-redis
  ports:
  - port: 6379
