#helm:generate helm template -o $HELM_GENERATE_DIR/manifests/deis-objectstorage-secret.yaml -d $HELM_GENERATE_DIR/tpl/generate_params.toml $HELM_GENERATE_DIR/tpl/deis-objectstorage-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-keyfile
  namespace: deis
  labels:
    heritage: deis
  annotations:
    deis.io/objectstorage: "{{ or (env "STORAGE_TYPE") (.storage)}}"
type: Opaque
data: {{ if or (eq (env "STORAGE_TYPE") "gcs") (eq .storage "gcs")}}
  key.json: {{ or (env "GCS_KEY_JSON") (.gcs.key_json) | b64enc}}
  registry-bucket: {{ or (env "GCS_REGISTRY_BUCKET") (.gcs.registry_bucket) | b64enc}}
  database-bucket: {{ or (env "GCS_DATABASE_BUCKET") (.gcs.database_bucket) | b64enc }}
  builder-bucket: {{ or (env "GCS_BUILDER_BUCKET") (.gcs.builder_bucket) | b64enc }}{{ else if or (eq (env "STORAGE_TYPE") "azure") (eq .storage "azure")}}
  accountname: {{ or (env "AZURE_ACCOUNT_NAME") (.azure.accountname) | b64enc }}
  accountkey: {{ or (env "AZURE_ACCOUNT_KEY") (.azure.accountkey) | b64enc }}
  registry-container: {{ or (env "AZURE_REGISTRY_CONTAINER") (.azure.registry_container) | b64enc }}
  database-container: {{ or (env "AZURE_DATABASE_CONTAINER") (.azure.database_container) | b64enc }}
  builder-container: {{ or (env "AZURE_BUILDER_CONTAINER") (.azure.builder_container) | b64enc }}{{ else if or (eq (env "STORAGE_TYPE") "s3") (eq .storage "s3")}}
  accesskey: {{ or (env "AWS_ACCESS_KEY") (.s3.accesskey) | b64enc }}
  secretkey: {{ or (env "AWS_SECRET_KEY") (.s3.secretkey) | b64enc }}
  region: {{ or (env "S3_REGION") (.s3.region) | b64enc }}
  registry-bucket: {{ or (env "AWS_REGISTRY_BUCKET") (.s3.registry_bucket) | b64enc }}
  database-bucket: {{ or (env "AWS_DATABASE_BUCKET") (.s3.database_bucket) | b64enc }}
  builder-bucket: {{ or (env "AWS_BUILDER_BUCKET") (.s3.builder_bucket) | b64enc }}{{ else if or (eq (env "STORAGE_TYPE") "swift") (eq .storage "swift")}}
  username: {{ or (env "SWIFT_USERNAME") (.swift.username) | b64enc }}
  password: {{ or (env "SWIFT_PASSWORD") (.swift.password) | b64enc }}
  authurl: {{ or (env "SWIFT_AUTHURL") (.swift.authurl) | b64enc }}
  tenant: {{ or (env "SWIFT_TENANT") (.swift.tenant) | b64enc }}
  authversion: {{ or (env "SWIFT_AUTHVERSION") (.swift.authversion) | b64enc }}
  registry-container: {{ or (env "SWIFT_REGISTRY_CONTAINER") (.swift.registry_container) | b64enc }}
  database-container: {{ or (env "SWIFT_DATABASE_CONTAINER") (.swift.database_container) | b64enc }}
  builder-container: {{ or (env "SWIFT_BUILDER_CONTAINER") (.swift.builder_container) | b64enc }}{{else if or (eq (env "STORAGE_TYPE") "minio") (eq .storage "minio")}}
  accesskey: OFRaUlkySlJXTVBUNlVNWFI2STU=
  secretkey: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZaw=={{ end }}
