apiVersion: v1
kind: Service
metadata:
  name: deis-registry
  namespace: deis
  labels:
    heritage: deis
  annotations:
    helm-keep: "true"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: deis-registry
