apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-registry-token-refresher
  namespace: deis
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{env "REGISTRY_TOKEN_REFRESH_GIT_TAG" | default .registry_token_refresher.dockerTag}}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-registry-token-refresher
  template:
    metadata:
      labels:
        app: deis-registry-token-refresher
    spec:
      containers:
        - name: deis-registry-token-refresher
          image: quay.io/{{.registry_token_refresher.org}}/registry-token-refresher:{{env "REGISTRY_TOKEN_REFRESH_GIT_TAG" | default .registry_token_refresher.dockerTag}}
          imagePullPolicy: {{.registry_token_refresher.pullPolicy}}
          env:
            - name: "DEIS_REGISTRY_LOCATION"
              value: "{{ or (env "REGISTRY_LOCATION") (.registry_location) }}"
            - name: "DEIS_REGISTRY_SECRET_PREFIX"
              value: "{{ .registry_token_refresher.secretPrefix }}"
            - name: DEIS_NAMESPACE_REFRESH_TIME
              value: "5"
            - name: "DEIS_TOKEN_REFRESH_TIME"
              value: "{{ or (env "DEIS_TOKEN_REFRESH_TIME") (.registry_token_refresher.tokenRefreshTime)}}"
          volumeMounts:
            - name: registry-secret
              mountPath: /var/run/secrets/deis/registry/creds
              readOnly: true
      volumes:
        - name: registry-secret
          secret:
            secretName: registry-secret
