apiVersion: v1
kind: Secret
metadata:
  name: logger-redis-creds
  namespace: deis
  labels:
    app: deis-logger-redis
    heritage: deis
  annotations:
    helm-keep: "true"
data:
  password: {{ if env "LOGGER_REDIS_LOCATION" | default .logger_redis_location | eq "off-cluster" }}{{ env "LOGGER_REDIS_PASSWORD" | default .loggerRedis.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
