#helm:generate helm tpl --out $HELM_GENERATE_DIR/manifests/deis-controller-secret-django-secret-key.yaml $HELM_GENERATE_DIR/tpl/deis-controller-secret-django-secret-key.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret-key
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  secret-key: {{ randAscii 64 | b64enc }}
