apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: {{ if env "DATABASE_LOCATION" | default .database_location | eq "off-cluster" }}{{ env "DATABASE_USERNAME" | default .database.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if env "DATABASE_LOCATION" | default .database_location | eq "off-cluster" }}{{ env "DATABASE_PASSWORD" | default .database.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
