name: router-v2.9.0
home: https://github.com/deis/router
version: v2.9.0
description: Deis Router
maintainers:
- Deis Team <engineering@deis.com>
details: |-
  The Deis Router is a simple program that manages Nginx and Nginx configuration for managing
  ingress to web applications in a Kubernetes cluster without requiring each to have their own
  external (to the cluster) load balancer.  Router(s) will require a single external load balancer,
  handle all ingress, and direct all incoming traffic to appropriate services within the cluster.

  Router works by regularly querying the Kubernetes API for services labeled with
  `router.deis.io/routable: "true"`. Such services are compared to known services resident in
  memory. If there are differences, new Nginx configuration is generated and Nginx is reloaded.

  NOTE: Kubernetes Helm has replaced Helm classic, so these charts are deprecated.
  Router v2.9.0 will be the last release installable with Helm classic (helmc).
  See https://github.com/deis/workflow-migration#workflow-migration for help upgrading
  to Kubernetes Helm, and see https://deis.com/docs/workflow/installing-workflow/ for
  general installation instructions.
