#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-workflow-secret-builder-key-auth.yaml --out $HELM_GENERATE_DIR/manifests/deis-workflow-secret-builder-key-auth.yaml
apiVersion: v1
kind: Secret
metadata:
  name: builder-key-auth
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  builder-key: {{ randAscii 64 | b64enc }}
