#!/usr/bin/env bash

set -eo pipefail -o nounset

if [ ${1:-""} == "-h" ]; then
  cat <<EOF

  You can set the following variables:

  IMAGE_PREFIX = "" | "quay.io/" | ...
  ORGANIZATION = "deis" | "deisci" | ...
  VERSION = "v2alpha" | "2.0.0-alpha" | ...

EOF

  exit 1
fi

if [ -z ${IMAGE_PREFIX+x} ]; then
  IMAGE_PREFIX=\\2
fi

find * -iname '*.yaml' | xargs sed -i .bak -E "s|^(.*)image: (quay\.io/)?(.*)/(.*):(.*)$|\1image: ${IMAGE_PREFIX}${ORGANIZATION:-\\3}/\4:${VERSION:-\\5}|g"

find * -name "Chart.yaml" | xargs sed -i .bak -E "s|^(.*)version: (.*)$|\1version: ${VERSION:-\\2}|g"

find deis -name "README.md" | xargs sed -i .bak -E "s|^# Deis (.*)$|# Deis ${VERSION:-\\1}|"


find * -name '*.bak' | xargs rm -f
