#helm:generate helm tpl -d $HELM_GENERATE_DIR/tpl/generate_params.toml -o $HELM_GENERATE_DIR/manifests/deis-workflow-manager-rc.yaml $HELM_GENERATE_DIR/tpl/deis-workflow-manager-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow-manager
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-workflow-manager
  template:
    metadata:
      labels:
        app: deis-workflow-manager
    spec:
      serviceAccount: deis-workflow-manager
      containers:
      - name: deis-workflow-manager
        image: quay.io/{{.workflowManager.org}}/workflow-manager:{{env "WORKFLOW_MANAGER_GIT_TAG" | default .workflowManager.dockerTag}}
        imagePullPolicy: {{.workflowManager.pullPolicy}}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WORKFLOW_MANAGER_PORT
          value: "8080"
        - name: WORKFLOW_MANAGER_VERSIONSAPIURL
          value: {{.workflowManager.versionsApiURL}}
        - name: WORKFLOW_MANAGER_DOCTORAPIURL
          value: "https://doctor.deis.com"
        - name: WORKFLOW_MANAGER_POLLING
          value: "43200"
        - name: WORKFLOW_MANAGER_CHECKVERSIONS
          value: "true"
        - name: WORKFLOW_MANAGER_APIVERSION
          value: "v2"
        - name: WORKFLOW_MANAGER_DEISNAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
