apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deis-logger-fluentd
  namespace: deis
  labels:
    heritage: deis
spec:
  template:
    metadata:
      name: deis-logger-fluentd
      labels:
        heritage: deis
    spec:
      serviceAccount: deis-logger-fluentd
      containers:
      - name: deis-logger-fluentd
        image: quay.io/deis/fluentd:v2-beta
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: "SYSLOG_HOST"
          value: $(DEIS_LOGGER_PORT_514_UDP_ADDR)
        - name: "SYSLOG_PORT"
          value: $(DEIS_LOGGER_PORT_514_UDP_PORT)
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
