#helm:generate helm tpl $HELM_GENERATE_DIR/tpl/deis-database-secret-creds.yaml --out $HELM_GENERATE_DIR/manifests/deis-database-secret-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: {{ randAscii 64 | b64enc }}
  password: {{ randAscii 64 | b64enc }}
