name: deis-tests
home: https://github.com/deis/workflow-e2e
version: v2-beta
description: End-to-end tests for Deis v2
maintainers:
- Deis Team <engineering@deis.com>
details: |-
  End-to-end (e2e) workflow tests for the Deis v2 open source PaaS.

  Deis (pronounced DAY-iss) is an open source PaaS that makes it easy to deploy
  and manage applications on your own servers. Deis builds on Kubernetes
  to provide a lightweight, Heroku-inspired workflow.
