apiVersion: v1
kind: Service
metadata:
  name: deis-minio
  labels:
    heritage: deis
spec:
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: deis-minio
