kind: ReplicationController
apiVersion: v1
metadata:
  name: deis-etcd-1
  labels:
    name: deis-etcd-1
spec:
  replicas: 3
  selector:
    name: deis-etcd-1
  template:
    metadata:
      labels:
        name: deis-etcd-1
    spec:
      volumes:
        - name: discovery-token
          secret:
            secretName: deis-etcd-discovery-token
      containers:
        - name: deis-etcd-1
          image: quay.io/deisci/etcd:v2-alpha
          imagePullPolicy: Always
          env:
            - name: DEIS_ETCD_CLUSTER_SIZE
              value: "3"
            - name: ETCD_NAME
              value: deis1
          volumeMounts:
            - name: discovery-token
              readOnly: true
              mountPath: /var/run/secrets/deis/etcd/discovery
