apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-registry
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    name: deis-registry
  template:
    metadata:
      labels:
        name: deis-registry
    spec:
      containers:
        - name: deis-registry
          image: registry:2
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          emptyDir: {}
