apiVersion: v1
kind: Service
metadata:
  name: deis-workflow
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    name: deis-workflow
