apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-database
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    name: deis-database
  template:
    metadata:
      labels:
        name: deis-database
    spec:
      containers:
        - name: deis-database
          image: postgres:9.3
          env:
            - name: POSTGRES_USER
              value: "deis"
            - name: POSTGRES_PASSWORD
              value: "changeme123"
          ports:
            - containerPort: 5432
