apiVersion: v1
kind: Service
metadata:
  name: deis-controller
  namespace: deis
  labels:
    heritage: deis
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: deis
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: deis-controller
