apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-influxui
  namespace: deis
  labels:
    heritage: deis
    app: deis-monitor-influxui
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: influx
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  ports:
  - port: 80
    name: admin
    targetPort: admin
  selector:
    app: deis-monitor-influxdb
