apiVersion: v1
kind: Service
metadata:
  name: deis-nsqd
  namespace: deis
  labels:
    heritage: deis
    app: deis-nsqd
spec:
  ports:
  - port: 4151
    name: http
    targetPort: http
  - port: 4150
    name: transport
    targetPort: transport
  selector:
    app: deis-nsqd
