apiVersion: v1
kind: Service
metadata:
  name: deis-ui
  namespace: deis
  labels:
    heritage: deis
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: www
spec:
  selector:
    app: deis-ui
  ports:
    - name: http
      port: 80
      targetPort: 9000
